# Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.
# Run ordered developer checks through Cargo on Windows, macOS and Linux.
# This package uses only the standard library and spawns Cargo directly.
# It does not require Make, Bash, Python or an installed task runner.
# Workspace configuration supplies convenient reader and workspace aliases.
# Failures stop the sequence and propagate to callers and CI.
[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-2.0-only"
