# Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.

"""Copyright requirement: preserve third-party/generated bytes and cover new source forms."""

from pathlib import Path

import pytest

from scripts.check_copyright import NOTICE, expected_header, is_eligible


@pytest.mark.parametrize("filename", [
    "website/static/images/hands-typing.svg", "gui/vendor/tabulator/tabulator.min.js",
    "website/themes/envelope-rainbow/templates/index.html", "tests/data/message.eml",
    "uv.lock", ".agents/skills/pr-to-ready/SKILL.md", ".claude/skills/pr-to-ready/SKILL.md",
    "CLAUDE.md", ".github/copilot-instructions.md",
])
def test_external_and_generated_material_is_not_claimed(filename: str) -> None:
    """New upstream artwork and generated workflows must not acquire project ownership notices."""
    assert not is_eligible(Path(filename))


@pytest.mark.parametrize("filename,comment", [
    ("typings/AppKit/__init__.pyi", f"# {NOTICE}"),
    ("gui/file-drag.mjs", f"/* {NOTICE} */"),
    ("src/mailarchiver/file_drag.py", f"# {NOTICE}"),
])
def test_new_source_formats_use_native_comments(filename: str, comment: str) -> None:
    """Current-main JavaScript modules and type stubs follow the same source notice policy."""
    path = Path(filename)
    assert is_eligible(path)
    assert expected_header(path) == comment
