"""Minimal AppKit selectors used by mailarchiver; no runtime replacement."""
from typing import Self
from Foundation import NSURL

NSPasteboardTypeString: str
NSPasteboardTypeFileURL: str
NSPasteboardTypeURL: str
NSFilenamesPboardType: str

class NSPasteboard:
    @classmethod
    def generalPasteboard(cls) -> Self: ...
    def clearContents(self) -> int: ...
    def setString_forType_(self, value: str, kind: str) -> bool: ...
    def setPropertyList_forType_(self, value: list[str], kind: str) -> bool: ...

class NSWorkspace:
    @classmethod
    def sharedWorkspace(cls) -> Self: ...
    def openURL_(self, url: NSURL) -> bool: ...

class NSImage:
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithContentsOfFile_(self, path: str) -> Self | None: ...
    @classmethod
    def imageWithSystemSymbolName_accessibilityDescription_(cls, name: str, description: str) -> Self | None: ...

class NSApplication:
    @classmethod
    def sharedApplication(cls) -> Self: ...
    def setMainMenu_(self, menu: object) -> None: ...
    def setApplicationIconImage_(self, image: NSImage) -> None: ...


NSTerminateCancel: int

class NSAlert:
    @classmethod
    def alloc(cls) -> Self: ...
    def init(self) -> Self: ...
    def setMessageText_(self, text: str) -> None: ...
    def setInformativeText_(self, text: str) -> None: ...
    def addButtonWithTitle_(self, title: str) -> object: ...
    def runModal(self) -> int: ...
