# Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.

"""Minimal Cocoa Foundation selectors used by mailarchiver."""
from typing import Any, Callable, Mapping, Self

class NSSet:
    @classmethod
    def setWithArray_(cls, values: list[str]) -> Self: ...

class NSDate:
    @classmethod
    def dateWithTimeIntervalSinceNow_(cls, seconds: float) -> Self: ...

class NSUserDefaults:
    @classmethod
    def standardUserDefaults(cls) -> Self: ...
    def registerDefaults_(self, values: Mapping[str, object]) -> None: ...
    def removePersistentDomainForName_(self, name: str) -> None: ...

class NSURL:
    @classmethod
    def fileURLWithPath_(cls, path: str) -> Self: ...
    @classmethod
    def URLWithString_(cls, value: str) -> Self | None: ...
    def path(self) -> str: ...
    def absoluteString(self) -> str: ...

class NSBundle:
    @classmethod
    def mainBundle(cls) -> Self: ...
    @classmethod
    def bundleWithPath_(cls, path: str) -> Self | None: ...
    def load(self) -> bool: ...
    def bundlePath(self) -> str: ...
    def privateFrameworksPath(self) -> str: ...
    def bundleIdentifier(self) -> str: ...
    def localizedInfoDictionary(self) -> dict[str, str] | None: ...
    def infoDictionary(self) -> dict[str, Any]: ...

class NSProcessInfo:
    @classmethod
    def processInfo(cls) -> Self: ...
    def setProcessName_(self, name: str) -> None: ...


class NSThread:
    @classmethod
    def isMainThread(cls) -> bool: ...

class NSTimer:
    @classmethod
    def timerWithTimeInterval_repeats_block_(cls, interval: float, repeats: bool, callback: Callable[[Self], None]) -> Self: ...
    @classmethod
    def scheduledTimerWithTimeInterval_repeats_block_(cls, interval: float, repeats: bool, callback: Callable[[Self], None]) -> Self: ...
    def invalidate(self) -> None: ...

class NSRunLoop:
    @classmethod
    def mainRunLoop(cls) -> Self: ...
    @classmethod
    def currentRunLoop(cls) -> Self: ...
    def runUntilDate_(self, date: NSDate) -> None: ...
    def addTimer_forMode_(self, timer: NSTimer, mode: str) -> None: ...

class NSNotificationCenter:
    @classmethod
    def defaultCenter(cls) -> Self: ...
    def addObserverForName_object_queue_usingBlock_(self, name: str, obj: object, queue: object, callback: Callable[..., object]) -> object: ...
    def removeObserver_(self, observer: object) -> None: ...
