"""Minimal Cocoa Foundation selectors used by mailarchiver."""
from typing import Self

class NSURL:
    @classmethod
    def fileURLWithPath_(cls, path: str) -> Self: ...
    @classmethod
    def URLWithString_(cls, value: str) -> Self | None: ...
    def absoluteString(self) -> str: ...

class NSBundle:
    @classmethod
    def mainBundle(cls) -> Self: ...
    def localizedInfoDictionary(self) -> dict[str, str] | None: ...
    def infoDictionary(self) -> dict[str, str]: ...

class NSProcessInfo:
    @classmethod
    def processInfo(cls) -> Self: ...
    def setProcessName_(self, name: str) -> None: ...
