// Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.
// Embed the application version from the canonical Python project manifest.
// Optional updater metadata is generated by the shared release-version mapper.
// The metadata's version must match the manifest before its build is embedded.
// Development builds without that metadata still display the correct version.
// Windows updater feeds and public keys are explicit build-time configuration.
// No compiler or end-user execution depends on Python at runtime.
use std::{env, fs};

fn main() {
    println!("cargo:rerun-if-changed=../../pyproject.toml");
    let manifest: toml::Value =
        toml::from_str(&fs::read_to_string("../../pyproject.toml").expect("read pyproject.toml"))
            .expect("parse pyproject.toml");
    let version = manifest["project"]["version"]
        .as_str()
        .expect("project version");
    println!("cargo:rustc-env=ECT_APP_VERSION={version}");
    for name in [
        "ECT_RELEASE_VERSION",
        "ECT_RELEASE_BUILD",
        "ECT_RELEASE_CHANNEL",
        "ECT_WINSPARKLE_APPCAST_URL",
        "ECT_WINSPARKLE_PUBLIC_KEY",
    ] {
        println!("cargo:rerun-if-env-changed={name}");
    }
    if let Ok(build) = env::var("ECT_RELEASE_BUILD") {
        assert_eq!(
            env::var("ECT_RELEASE_VERSION").as_deref(),
            Ok(version),
            "release metadata must match pyproject.toml"
        );
        assert!(build.parse::<u64>().expect("numeric mapped release build") > 0);
        let channel = env::var("ECT_RELEASE_CHANNEL").expect("mapped release channel");
        assert!(matches!(channel.as_str(), "preview" | "release"));
        println!("cargo:rustc-env=ECT_RELEASE_BUILD={build}");
        println!("cargo:rustc-env=ECT_RELEASE_CHANNEL={channel}");
    }
}
